# Generated by Django 5.0.6 on 2024-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_text', models.TextField()),
                ('blog_Img', models.ImageField(upload_to='blog')),
                ('blog_date', models.DateField(auto_now_add=True)),
                ('BlogUpdate_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
