# Generated by Django 5.0.6 on 2024-05-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_Img',
            field=models.ImageField(upload_to='image'),
        ),
    ]
